name: ESLint
on:
  push:
    branches:
      - '**'
      - 'staging'
      - '!docs'
      - '!master'
      - '!gh-pages'
  pull_request:
    branches:
      - 'staging'
      - '!docs'
      - '!master'
      - '!gh-pages'
jobs:
  test:
    name: ESLint (Node v18)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: 📥 Install Node v18
        uses: actions/setup-node@master
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
